### ISSUE TITLE
enable single quote eslint rule

### ISSUE THREAD

**Issue by MiguelCastillo** [MiguelCastillo/bit-loader#164]

**Comment by MiguelCastillo** [comment]
@IanVS If you wanna take a crack a this... :)

**Comment by IanVS** [comment]
Sure I'll work on it tonight.

**Comment by IanVS** [comment]
Hm, You sure you want `single`?  You have 913 errors when set to `single`, and only 72 when set to `double`.

**Comment by MiguelCastillo** [comment]
Meh, lets go with double quotes :)

**Comment by IanVS** [comment]
It's a good chance to test out the new ESLint [autofix PR](https://github.com/eslint/eslint/pull/3635).

**Comment by MiguelCastillo** [comment]
Sounds great!
