### ISSUE TITLE
Create .npmignore to prevent tests and src being pushed to npm.

### ISSUE THREAD

**Issue by Mark-Simulacrum** [MiguelCastillo/bit-loader#5]
Since `npm` does not need tests or the source, we can ignore those when publishing to npm using npmignore.

**Comment by MiguelCastillo** [comment]
Good call

**Comment by MiguelCastillo** [comment]
Done https://github.com/MiguelCastillo/bit-loader/commit/45e2d6bfe12a1e7f7949c3f7872774c2430c1a6b
