### ISSUE TITLE
Utils.merge overrides properties in input data

### ISSUE THREAD

**Issue by MiguelCastillo** [MiguelCastillo/bit-loader#9]

**Comment by MiguelCastillo** [comment]
@Mark-Simulacrum I just fixed it with https://github.com/MiguelCastillo/bit-loader/commit/99c2afa447bc42b8b6ce2bf0f16e61bd9331a940

There was more to it.  The bug was that arrays were incorrectly treated as objects, which was causing merge to incorrectly process array elements as object properties

**Comment by Mark-Simulacrum** [comment]
That works too :)
